name: order-service

image:
  repository: ""
  tag: latest

replicaCount: 2
port: 3000

service:
  type: ClusterIP

probes:
  path: /health

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

configData:
  DB_HOST: postgres-db
  DB_NAME: ordersdb
  USER_SERVICE_URL: http://user-service:3000
  PRODUCT_SERVICE_URL: http://product-service:3000
  NOTIFICATION_SERVICE_URL: http://notification-service:3000
  OTEL_SERVICE_NAME: order-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-collector.observability.svc.cluster.local:4318

secret:
  enabled: true
  data:
    DB_USER: postgres
    DB_PASSWORD: postgres
