apiVersion: v2
name: ecommerce-app
description: Chart parent orchestrant les 6 microservices + 2 bases de données
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
  - name: mongo
    version: 0.1.0
    repository: "file://charts/mongo"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: api-gateway
    version: 0.1.0
    repository: "file://charts/api-gateway"
  - name: user-service
    version: 0.1.0
    repository: "file://charts/user-service"
  - name: product-service
    version: 0.1.0
    repository: "file://charts/product-service"
  - name: order-service
    version: 0.1.0
    repository: "file://charts/order-service"
  - name: notification-service
    version: 0.1.0
    repository: "file://charts/notification-service"
