name: product-service

image:
  repository: ""
  tag: latest

replicaCount: 2
port: 3000

service:
  type: ClusterIP

probes:
  path: /health

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

configData:
  MONGO_URI: mongodb://mongo-db:27017/products
  OTEL_SERVICE_NAME: product-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-collector.observability.svc.cluster.local:4318

secret:
  enabled: false
  data: {}
