name: Build, Scan & Push images vers ECR

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECR_REPO_PREFIX: orchestration-eks

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - frontend
          - api-gateway
          - user-service
          - product-service
          - order-service
          - notification-service

    steps:

      # 1. Récupération du code
      - name: Récupérer le code
        uses: actions/checkout@v4

      # 2. Construction de l'image Docker
      - name: Build de l'image ${{ matrix.service }}
        run: |
          docker build \
            -t local/${{ matrix.service }}:scan \
            ./ecommerce-app/${{ matrix.service }}

      # 3. Scan de vulnérabilités
      - name: Scan de vulnérabilités avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: local/${{ matrix.service }}:scan
          format: table
          severity: CRITICAL,HIGH
          exit-code: "1"
          ignore-unfixed: true

      # 4. Authentification AWS avec OIDC
      - name: Authentification AWS (OIDC)
        if: github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 5. Connexion à ECR
      - name: Login sur Amazon ECR
        if: github.event_name != 'pull_request'
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      # 6. Tag et Push vers ECR
      - name: Push de l'image vers ECR
        if: github.event_name != 'pull_request'
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag \
            local/${{ matrix.service }}:scan \
            $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:$IMAGE_TAG

          docker tag \
            local/${{ matrix.service }}:scan \
            $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:latest

          docker push \
            $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:$IMAGE_TAG

          docker push \
            $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:latest