name: Build & Push images vers ECR

on:
  push:
    branches: [main]
    paths:
      - "ecommerce-app/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3
  ECR_REPO_PREFIX: orchestration-eks

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - api-gateway
          - user-service
          - product-service
          - order-service
          - notification-service

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Authentification AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login sur Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build et push de l'image ${{ matrix.service }}
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:$IMAGE_TAG \
                        -t $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:latest \
                        ./ecommerce-app/${{ matrix.service }}
          docker push $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO_PREFIX/${{ matrix.service }}:latest